version: '2.0'

services:

  web:
    build: web
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    user: "root"
    volumes:
      - ./web:/home/node/app
      - /home/node/app/node_modules

volumes:
  data: {}
  public: {}
